---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: dry-run-base
  pull: always
  image: plugins/docker
  settings:
    context: docker/base
    dockerfile: docker/base/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: base
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: dry-run-go-1.12.5
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.5
    dockerfile: docker/go-1.12.5/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.5
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: dry-run-go-1.11.10
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.11.10
    dockerfile: docker/go-1.11.10/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.11.10
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: build-base
  pull: always
  image: plugins/docker
  settings:
    context: docker/base
    dockerfile: docker/base/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: base
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.5
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.5
    dockerfile: docker/go-1.12.5/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.5
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.x
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.x
    dockerfile: docker/go-1.12.x/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.x
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-latest
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-latest
    dockerfile: docker/go-latest/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: latest
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.11.10
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.11.10
    dockerfile: docker/go-1.11.10/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.11.10
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.11.x
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.11.x
    dockerfile: docker/go-1.11.x/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.11.x
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.4
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.4
    dockerfile: docker/go-1.12.4/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.4
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.3
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.3
    dockerfile: docker/go-1.12.3/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.3
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.2
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.2
    dockerfile: docker/go-1.12.2/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.2
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.1
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.1
    dockerfile: docker/go-1.12.1/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.1
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.12.0
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.12.0
    dockerfile: docker/go-1.12.0/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.12.0
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.11.9
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.11.9
    dockerfile: docker/go-1.11.9/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.11.9
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

...
