---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: dry-run-base
  pull: always
  image: plugins/docker
  settings:
    context: docker/base
    dockerfile: docker/base/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: base
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: dry-run-go-1.15.0
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.15.0
    dockerfile: docker/go-1.15.0/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.15.0
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: dry-run-go-1.14.7
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.14.7
    dockerfile: docker/go-1.14.7/Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.14.7
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: build-base
  pull: always
  image: plugins/docker
  settings:
    context: docker/base
    dockerfile: docker/base/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: base
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: build-go-1.15.0
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.15.0
    dockerfile: docker/go-1.15.0/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.15.0
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  depends_on:
  - build-base

- name: build-go-1.15.x
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.15.x
    dockerfile: docker/go-1.15.x/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.15.x
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  depends_on:
  - build-go-1.15.0

- name: build-go-1.14.7
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.14.7
    dockerfile: docker/go-1.14.7/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.14.7
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  depends_on:
  - build-base

- name: build-go-1.14.x
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-1.14.x
    dockerfile: docker/go-1.14.x/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: go-1.14.x
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  depends_on:
  - build-go-1.14.7

- name: build-go-latest
  pull: always
  image: plugins/docker
  settings:
    context: docker/go-latest
    dockerfile: docker/go-latest/Dockerfile
    password:
      from_secret: docker_password
    repo: techknowlogick/xgo
    tags: latest
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
  depends_on:
  - build-go-1.15.x

...
