{
   "kind": "pipeline",
   "name": "default",
   "steps": [
      {
         "name": "dry-run-base",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/base/Dockerfile",
            "context": "docker/base",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "base",
            "dry_run": true
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      },
      {
         "name": "dry-run-go-1.13.4",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.13.4/Dockerfile",
            "context": "docker/go-1.13.4",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.13.4",
            "dry_run": true
         },
         "depends_on": [
            "dry-run-base"
         ],
         "when": {
            "event": [
               "pull_request"
            ]
         }
      },
      {
         "name": "dry-run-go-1.12.13",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.12.13/Dockerfile",
            "context": "docker/go-1.12.13",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.12.13",
            "dry_run": true
         },
         "depends_on": [
            "dry-run-base"
         ],
         "when": {
            "event": [
               "pull_request"
            ]
         }
      },
      {
         "name": "build-base",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/base/Dockerfile",
            "context": "docker/base",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "base",
            "dry_run": false
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      },
      {
         "name": "build-go-1.13.4",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.13.4/Dockerfile",
            "context": "docker/go-1.13.4",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.13.4",
            "dry_run": false
         },
         "depends_on": [
            "build-base"
         ],
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      },
      {
         "name": "build-go-1.13.x",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.13.x/Dockerfile",
            "context": "docker/go-1.13.x",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.13.x",
            "dry_run": false
         },
         "depends_on": [
            "build-go-1.13.4"
         ],
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      },
      {
         "name": "build-go-1.12.13",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.12.13/Dockerfile",
            "context": "docker/go-1.12.13",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.12.13",
            "dry_run": false
         },
         "depends_on": [
            "build-base"
         ],
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      },
      {
         "name": "build-go-1.12.x",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-1.12.x/Dockerfile",
            "context": "docker/go-1.12.x",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "go-1.12.x",
            "dry_run": false
         },
         "depends_on": [
            "build-go-1.12.13"
         ],
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      },
      {
         "name": "build-go-latest",
         "pull": "always",
         "image": "plugins/docker",
         "settings": {
            "dockerfile": "docker/go-latest/Dockerfile",
            "context": "docker/go-latest",
            "password": {
               "from_secret": "docker_password"
            },
            "username": {
               "from_secret": "docker_username"
            },
            "repo": "techknowlogick/xgo",
            "tags": "latest",
            "dry_run": false
         },
         "depends_on": [
            "build-go-1.13.x"
         ],
         "when": {
            "branch": [
               "master"
            ],
            "event": {
               "exclude": [
                  "pull_request"
               ]
            }
         }
      }
   ]
}
