# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
# Copyright (c) 2019 The Gitea Authors. All rights reserved.
#
# Released under the MIT license.

FROM techknowlogick/xgo:go-1.15.x

LABEL maintainer="techknowlogick <techknowlogick@gitea.io>"
