# Go cross compiler (xgo): Go 1.11.x
# Copyright (c) 2018 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM techknowlogicx/xgo:go-1.11.6

LABEL maintainer="Péter Szilágyi <peterke@gmail.com>"
